# This is a config for E2B sandbox template.
# You can use template ID (6k320phxs0cve82nxfyy) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("6k320phxs0cve82nxfyy") # Sync sandbox
# sandbox = await AsyncSandbox.create("6k320phxs0cve82nxfyy") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('6k320phxs0cve82nxfyy')

team_id = "3f251570-a7aa-46d1-89b4-a8f5466b12fd"
dockerfile = "e2b.Dockerfile"
template_id = "6k320phxs0cve82nxfyy"
